### ISSUE TITLE
Enemy skills handled improperly on initial load

### ISSUE THREAD

**Issue by Soaprman** [Soaprman/FEFTwiddler#16]
Not sure if this is a bug yet, but it probably is.

Steps:
* Pick a save where a character knows an enemy skill
* Make sure "Include enemy skills" is not checked
* Go to that character
* See what happens. I think I want it to show the enemy skill but it probably won't.

Maybe detection is needed when loading a character to see which data source to default to.

**Comment by rilne** [comment]
The skill icon shows up correctly, but the name doesn't (and it's not `none`, either).
