### ISSUE TITLE
Auto-backup when opening file

### ISSUE THREAD

**Issue by rilne** [Soaprman/FEFTwiddler#19]
Save a backup of the last successfully opened file to `ChapterX.bin.autobak` or similar, so if they bork their file, they at least have the most recent good one they worked on to fall back on.

(this should be an enhancement, but I don't appear to have rights to mark it as such)

**Comment by Soaprman** [comment]
Good thinking. I'll mark it, and maybe figure out how to give you those permissions.

**Comment by Soaprman** [comment]
Now, when you save a file, a timestamped backup is created before saving.
