### ISSUE TITLE
Accessory classes should be combined into one class.

### ISSUE THREAD

**Issue by RainThunder** [Soaprman/FEFTwiddler#32]
I think accessory classes (Headwear, Facewear, Armwear, Underwear) should be combined into one class. Accessory type could be read from database.

**Comment by Soaprman** [comment]
Sounds like a good idea. I'll look into this next time I'm in the neighborhood.

**Comment by RainThunder** [comment]
I will implement this in the next few days if you don't beat me to it.

My priority right now is stat editing. Do you have any save file with bond units? If so, could you test the new stat implementation for those units?

**Comment by Soaprman** [comment]
There are some in one of the test saves in FEFTwiddlerTest, either 9hopper or EldinTokuro (I forget which one). You can try now ifbyou want, or u can when i get home.

**Comment by RainThunder** [comment]
Thanks, I will try.

**Comment by Soaprman** [comment]
I'll leave this to you. I think I'm going to focus on bug fixes (mostly involving skills) this week, along with other features enabled by the recent Character.cs and ChapterSave.cs refactors.

**Comment by Soaprman** [comment]
By the way, if you get any saves from people, feel free to add them to the TestSaves folder. That'll make them accessible to anyone and include them in unit tests.
