### ISSUE TITLE
Level cap needs lowered from 235/255 to 100/120

### ISSUE THREAD

**Issue by Soaprman** [Soaprman/FEFTwiddler#33]
According to that girl:

The game's "true" limit is 255 (FF) for all classes, unpromoted, special, and promoted. HOWEVER, each eternal seal adds 5 levels to the cap of a promoted or special class. You can only use 16 scrolls per unit, meaning legitimately, promoted classes can reach a saved level of 100 (0x64) which the game adds 20 to when doing level calculations, and special classes reach a legitimate cap of 120, because they are never a promoted class, and have a starting cap of 40 instead of 20. And non-special unpromoted classes have a legitimate cap of 20, because they start with a level cap of 20 and don't benefit from eternal seal points.

**Comment by Otaku-chan** [comment]
Yeah, I figured that may be the case, bat actually, after some tests, you're right, 235/255.
We also learned that you can still use Eternal Seals at those level.

But it stands true that you can still set a non-special unpromoted unit to level 255 is you wanted, dispite the level 20 game rule limit.

**Comment by Soaprman** [comment]
Closing this issue. I guess reopen if we still have level problems!
