### ISSUE TITLE
Stat gains show 0 when GainedStats are 99 and BaseStats are above 28

### ISSUE THREAD

**Issue by Soaprman** [Soaprman/FEFTwiddler#41]
Steps:
* Apply the max stats megacheat
* Pick any character with high base stats (like Ryoma)
* Notice HP shows 0

This is because the GainedStats and BaseStats (see StatUtil/CalculateTrueStats) add up to more than 127, the ceiling for a sbyte.

**Comment by RainThunder** [comment]
Just set the character's base stats to his / her caps should solve the problem. However, if that character changes to another class, his / her stats might not be capped.

**Comment by Soaprman** [comment]
I think this is fixed now.
