### ISSUE TITLE
All bond units are set to gender="Male" in Characters.xml

### ISSUE THREAD

**Issue by Soaprman** [Soaprman/FEFTwiddler#44]
Probably half of them should be changed to Female.

Gonna just leave filling this in to somebody who knows who all these wacky people are, since I'd rather not have to guess based on their names!

**Comment by RainThunder** [comment]
I added "isFemale" flag for a while ago. You can change the database file based on that flag.

**Comment by Soaprman** [comment]
Huh, I completely overlooked that.

Is the "isFemale" flag more true to the way the game handles things? And if so, does it work the same for classes? The purpose of setting these is to get values right for the class picker, which I just enabled a bit ago.

**Comment by RainThunder** [comment]
Yes, they are how the game handles things. Same for classes.

**Comment by Soaprman** [comment]
Alright, I'll drop the Gender enum and switch the implementation to that, then.
