### ISSUE TITLE
pegasus knight

### ISSUE THREAD

**Issue by MattyO2** [Soaprman/FEFTwiddler#48]

**Comment by MattyO2** [comment]
oops
meant to say that when using the mega cheat for pegasus knight, it should change the 02-10 block in raw data 2 from 00 to 02 in order to make it selectable with heart seal

also, for the raw value on any weapon in the unit viewer, it should be decreased by 40 when the weapon is unchecked, since when it stays as 41 or such, the weapon ends up being forged to +63

**Comment by Soaprman** [comment]
I'll write up the equipment thing separately.

As for the pegasus knight thing, do you mean changing class? Also, would you have a list of values for the heart seal bytes? I'd rather not implement that unless it's complete for other classes too.

**Comment by MattyO2** [comment]
yes, changing it to 02 makes it selectable when changing classes with a heart seal. it adds pegasus knight to the "memory" of that character so they can use normally.

that byte is only used for *actual* DLC classes. and so far, pegasus knight is the only one that exists. the way to determine an actual DLC class is the same as awakening: it's not on the cart to start with, and battling other people without that DLC will give a placeholder class. dread fighter and bride were replaced with a grandmaster lookalike, and pegasus knight is replaced with a hooded figure that was used as the boss in chapter 5.

the bytes that come right before it are already correctly changed to FF when the all DLC cheat is clicked, and that correctly adds those classes like witch, vanguard, and the others to the characters' "heart seal memory". those classes were on the game cartridge to begin with, they work with people who haven't bought those respective DLCs, and so they're stored differently and are also already accounted for, compared to pegasus knight

I hope that's clear, but what I'm saying is that the 02 byte really is the only change that needs to be made

**Comment by Soaprman** [comment]
Added. I don't have access to the Cipher DLC, so it'll be up to you to tell me if this works as it should after the next release!
