### ISSUE TITLE
DLC Character IDs

### ISSUE THREAD

**Issue by DeathChaos25** [Soaprman/FEFTwiddler#5]
I don't know how many people have tried using this with my DLC, but I think it's better if I just give you the IDs for characters and stuff I'm working on;
Chrom = 0x600
Frederick = 0x601
Lissa = 0x602
Garon = 0x603
Mikoto = 0x604
Sumeragi = 0x605
Lilith = 0x606
Arete = 0x607

**Comment by RainThunder** [comment]
I think adding this is not really necessary. Data of those character can still be displayed properly, even if their ID is not known by the editor.

**Comment by Soaprman** [comment]
Do they have those same IDs when you encounter them in the story/DLC chapters? If so, I'll add them. Otherwise, eh, I'm kind of iffy on the idea of adding hack-specific IDs for the time being.

**Comment by Soaprman** [comment]
Are there any special Class IDs that go with these? I'm thinking I might add them just to save myself a few posts in the gbatemp thread.

**Comment by DeathChaos25** [comment]
Chrom's Lord class is 0x81
Frederick's unique Great Knight Class is 0x82
Lissa's Cleric class is 0x83

Frederick's unique GK class should no longer be in use, but for reference,
these are the same in DLC values, nothing was changed.

**Comment by Otaku-chan** [comment]
There's more than one GK class?
They don't just use a unique model, literally an second GK class?

**Comment by DeathChaos25** [comment]
Yes, because of how IS made them.
Every character has an AID block, which is an asset resource block, it determines with Hair, hair texture and/or color, face, face texture, voice, any unique costumes, and any unique animations.

The same is done with classes, they have a JID asset resource block that tells the game what animations the class uses, and the default model for it.

However, IS decided, to make no JID for these classes, as such, the class models were hard coded into their AID, hence me making the comments where i stated that "Their models are stuck to their head" which was also causing reclass glitches and what not.

Also, as far as internal names go, Chrom's Lord class is "ChromMale", Lissa's class is "SisterFemale", and Frederick's Great Knight class is "FrederickMale", Future Past Owain/Inigo/Severa also suffer from this, Severa and Inigo are not Mercenaries, they are their own Unique class, same with Owain, meaning if you simply port them they would suffer from the same issues that Chrom/Lissa/Frederick initially suffered from before being Fixed.

**Comment by Soaprman** [comment]
While I'm in the neighborhood, I'm going to close this. Addon data support was added with 0.17.0, and I believe the sample data I included in AddonData.zip files with the past few releases covers this (I see these IDs in the XML).
