### ISSUE TITLE
Saved files are cut short

### ISSUE THREAD

**Issue by INSYG** [Soaprman/FEFTwiddler#58]
(What a wonder it is that I somehow manage to look into save editing for this game the same day this starts getting updated again.)

Saving a file with versions 0.17.0 and 0.17.1 (even without changing any values) outputs a smaller file, which is identical to the original file until location 0x39ED (for my file, uncompressed), and the file ends shortly after. This doesn't seem to happen with 0.16.0.

[Chapter1.zip](https://github.com/Soaprman/FEFTwiddler/files/574185/Chapter1.zip)

**Comment by Soaprman** [comment]
This is the thing I was kind of worried would happen when I added the building stuff. I'll go ahead and get a fix out for this ASAP.

**Comment by Soaprman** [comment]
This will be in 0.17.2, which will be uploaded in about a minute.
