### ISSUE TITLE
Hex Editor overwrites values without saving

### ISSUE THREAD

**Issue by INSYG** [Soaprman/FEFTwiddler#59]
(Report 2: Electric Bug-aloo)

Changing the values in the Hex Editor (from the Unit Viewer) will overwrite the previous values, even if the "Save and Close" button isn't pressed (by pressing "Cancel" or closing the Hex Editor). "RawBlock1" and "RawInventory" are unaffected and revert to their original values (as intended).

**Comment by Soaprman** [comment]
Not sure why some were working and some weren't, but this should hopefully take care of that.
