### ISSUE TITLE
Invalid Raw item data doesn't update properly

### ISSUE THREAD

**Issue by INSYG** [Soaprman/FEFTwiddler#60]
(I'm oddly compelled to say something before all of these.)

Attempting to check the "Equipped" box for a non-weapon item (i.e. Heal, Vulnerary) will still add 0x40 to the 4th byte of that item. The "Equipped" box remains unchecked, and clicking it again does not change the value.

Afterward, if the item has more than 7 "Charges" (the maximum value of "Forges"), changing the item in that slot to a weapon will not update the Raw data at all. (Item ID and Equipped/Forges/Charges will still be those of the old item.) Changing the "Forges" or "Charges" values will fix the Raw data.

Similar to #49.

**Comment by Soaprman** [comment]
That should be everything, I think! I mean, unless something else gets found with this, that is.
