### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by KingEnma** [Soaprman/FEFTwiddler#67]
So I used this to give my file 99 of all gems and crops. and also used it to give me all character weapons (like Xander's lance, Hana's Katana etc.) to give max number of Dragon herbs, eternal seals, ganglari (reward version) and change some stats around. but when i restore the file that these changes are made on and get to where i select what file i want to play the screen goes black before the game closes and i get the message 'an error occurred, software was forcibly ended please restart the system and try again.

**Comment by Soaprman** [comment]
Open your backup save in FEFTwiddler, make no changes, save, and see if it works. Then repeat, but make only one change each time until you figure out the culprit. Once you do, create a new issue and upload your save and I'll take a look next time I'm working on FEFTwiddler.
