### ISSUE TITLE
File Open dialogue suggestion

### ISSUE THREAD

**Issue by DoumanAsh** [Soaprman/FEFTwiddler#8]
1. Remove default name openFileDialogue1 of file. Just leave it empty i suppose? It is kinda strange name for file :)
2. set RestoreDirectory = true
3. set InitialDirectory to Application.StartupPath

**Comment by Soaprman** [comment]
You mean you don't name all your files openFileDialog1?

Good idea, though. I think what I might actually do is save the directory chosen to a settings file and just have it default to that.

**Comment by DoumanAsh** [comment]
Lol well skipping the first thing as it is quite minor i believe it would be good to add 2 and 3 properties to improve usability.
RestoreDirectory should let you open new dialogue at the same place where you left last time.
And initialDirectory is good idea either to be binary's path or configured by user 

I could add PR but i thought it would be better to leave to you.

**Comment by Soaprman** [comment]
Done. I'm not going to put out a new release just for this, but you're welcome to give it a spin!

**Comment by DoumanAsh** [comment]
Cool, i actually did not mean to do such a complex solution but to just adjust some attributes for this File dialogue, but that's cool

**Comment by Soaprman** [comment]
Yeah, I just figured I might as well make it persist after closing and reopening the program while I was at it.
