### ISSUE TITLE
DLC Skill adding suggestion

### ISSUE THREAD

**Issue by DoumanAsh** [Soaprman/FEFTwiddler#9]
Make separate option to add DLC skills?
As far as i know you're adding only original skills as of now, but if you're planning to add DLC skills it would be better to be as separate button/option and etc

**Comment by Soaprman** [comment]
I'll add this if I ever learn which bits in the learned skills block represent the DLC skills. Maybe once all the DLC stuff is available here in NA, I'll figure it out and add it.

**Comment by Otaku-chan** [comment]
Actually, I have a file with the bit location of all the skills. would you like it?

**Comment by Soaprman** [comment]
Sure! That'll help a lot.

**Comment by Otaku-chan** [comment]
[Here](http://download1654.mediafire.com/hvy108xptuvg/17a6hx5nh007hwh/Skill+Binary+Order.txt).

**Comment by Otaku-chan** [comment]
The emptyspace is used when the have no skills in the first byte, (01 instead of 00) but otherwise goes on used, it seems.

**Comment by Soaprman** [comment]
Thanks! This'll help speed skill stuff along.

**Comment by Soaprman** [comment]
Gonna close this issue now since learning skills got split into a few buttons. It could conceivably be split a bit more but we'll let that be brought up separately if needed.
